# Generated by Django 6.1 on 2026-09-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('game_started', 'Game started'), ('game_completed', 'Game completed'), ('quiz_started', 'Quiz started'), ('quiz_completed', 'Quiz completed'), ('question_answered', 'Question answered'), ('hint_used', 'Hint used'), ('xp_earned', 'XP earned'), ('coin_earned', 'Coin earned'), ('coin_spent', 'Coin spent'), ('badge_earned', 'Badge earned'), ('topic_completed', 'Topic completed')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_ef40a5_idx'), models.Index(fields=['student', 'created_at'], name='analytics_e_student_4a77e7_idx')],
            },
        ),
    ]
