# Generated by Django 6.1 on 2026-09-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['grade__order', 'subject__order', 'order'], 'verbose_name': 'chapter', 'verbose_name_plural': 'chapters'},
        ),
    ]
