# Generated by Django 6.1 on 2026-09-19 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('import_type', models.CharField(choices=[('curriculum', 'Curriculum Hierarchy'), ('questions', 'Questions / Mock Test Bank'), ('game_content', 'Game Content / Mechanics'), ('quizzes', 'Quizzes & Mock Tests')], max_length=40)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Validation'), ('validated', 'Validated (Ready for Import)'), ('imported', 'Imported Successfully'), ('failed', 'Validation Failed (Errors Found)'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('preview_data', models.JSONField(blank=True, default=list)),
                ('all_parsed_rows', models.JSONField(blank=True, default=list)),
                ('import_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Import Audit Log',
                'verbose_name_plural': 'Bulk Import Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
