# Generated by Django 6.1 on 2026-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Student phone number in E.164 format (e.g. +919876543210).', max_length=20, null=True, unique=True),
        ),
    ]
