# Generated by Django 6.1 on 2026-09-19 21:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
        ('assessments', '0001_initial'),
        ('curriculum', '0002_alter_topic_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=1800, help_text='Duration in seconds (e.g. 1800 = 30 minutes).')),
                ('passing_percentage', models.PositiveSmallIntegerField(default=60)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_tests', to='curriculum.grade')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_tests', to='curriculum.subject')),
            ],
            options={
                'verbose_name': 'Mock Test',
                'verbose_name_plural': 'Mock Tests',
                'ordering': ['grade__order', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted')], default='in_progress', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('percentage', models.PositiveSmallIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.mocktest')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mock_test_attempts', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Mock Test Attempt',
                'verbose_name_plural': 'Mock Test Attempts',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MockTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='assessments.mocktest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_mock_tests', to='assessments.question')),
            ],
            options={
                'verbose_name': 'Mock Test Question',
                'verbose_name_plural': 'Mock Test Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='mocktest',
            name='questions',
            field=models.ManyToManyField(related_name='mock_tests', through='assessments.MockTestQuestion', to='assessments.question'),
        ),
        migrations.CreateModel(
            name='MockTestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_correct', models.BooleanField(help_text='Null until answered.', null=True)),
                ('marks_awarded', models.SmallIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.mocktestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_responses', to='assessments.question')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_mock_responses', to='assessments.option')),
            ],
            options={
                'verbose_name': 'Mock Test Response',
                'verbose_name_plural': 'Mock Test Responses',
            },
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['student', 'mock_test'], name='assessments_student_65ce03_idx'),
        ),
        migrations.AddIndex(
            model_name='mocktestattempt',
            index=models.Index(fields=['student', 'status'], name='assessments_student_e4f2cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='mocktestquestion',
            constraint=models.UniqueConstraint(fields=('mock_test', 'question'), name='unique_question_per_mock_test'),
        ),
        migrations.AddIndex(
            model_name='mocktest',
            index=models.Index(fields=['grade', 'status'], name='assessments_grade_i_7b5386_idx'),
        ),
        migrations.AddConstraint(
            model_name='mocktestresponse',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_response_per_mock_attempt_question'),
        ),
    ]
