# Generated by Django 6.1 on 2026-09-09 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under review'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('game_type', models.CharField(choices=[('fraction_pizza', 'Fraction pizza'), ('science_sim', 'Science simulation'), ('matching', 'Matching game'), ('other', 'Other')], default='other', max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('access_tier', models.CharField(choices=[('free', 'Free'), ('trial', 'Trial-eligible'), ('premium', 'Premium')], default='free', max_length=10)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='curriculum.topic')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=20)),
                ('score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(blank=True, help_text='0.0–1.0', null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('correct_actions', models.PositiveIntegerField(default=0)),
                ('wrong_actions', models.PositiveIntegerField(default=0)),
                ('client_result_payload', models.JSONField(blank=True, null=True)),
                ('reward_granted', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='games.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['topic', 'status'], name='games_game_topic_i_3eb68c_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['student', 'game'], name='games_games_student_b4fd2b_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status'], name='games_games_status_e6c8c2_idx'),
        ),
    ]
