# Generated by Django 6.1 on 2026-09-09 13:14

from django.db import migrations


def migrate_topics_to_concepts(apps, schema_editor):
    Game = apps.get_model('games', 'Game')
    Concept = apps.get_model('curriculum', 'Concept')
    for game in Game.objects.all():
        if game.topic:
            first_concept = Concept.objects.filter(topic=game.topic).first()
            if first_concept:
                game.concept = first_concept
                game.save(update_fields=['concept'])


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_concept_alter_game_topic'),
    ]

    operations = [
        migrations.RunPython(migrate_topics_to_concepts, reverse_code=migrations.RunPython.noop),
    ]
