# Generated by Django 6.1 on 2026-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('games', '0003_migrate_game_topics_to_concepts'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='game',
            name='games_game_topic_i_3eb68c_idx',
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['concept', 'status'], name='games_game_concept_3f684a_idx'),
        ),
        migrations.RemoveField(
            model_name='game',
            name='topic',
        ),
    ]
