# Generated by Django 6.1 on 2026-09-13 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_games_game_topic_i_3eb68c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('prompt', models.CharField(blank=True, help_text='Question text or level objective', max_length=255)),
                ('content_type', models.CharField(default='standard', help_text='e.g. read_number, build_number, quiz_choice, etc.', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Flexible game-specific payload (targets, options, assets)')),
                ('correct_answer', models.JSONField(blank=True, help_text='Expected answer or rule for verification', null=True)),
                ('points', models.PositiveIntegerField(default=10)),
                ('hints', models.JSONField(blank=True, default=list, help_text='List of hints for students')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='games.game')),
            ],
            options={
                'verbose_name': 'game content / question',
                'verbose_name_plural': 'game contents / questions',
                'ordering': ['game', 'order'],
            },
        ),
    ]
