# Generated by Django 6.1 on 2026-09-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, default='other', max_length=50),
        ),
    ]
