# Generated by Django 6.1 on 2026-09-09 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('icon_key', models.CharField(blank=True, help_text='Frontend icon/asset identifier.', max_length=50)),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='XPLevelThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(unique=True)),
                ('xp_required', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CreditAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='XPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='xp_account', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Positive for earn/bonus/refund, negative for spend.')),
                ('transaction_type', models.CharField(choices=[('earn', 'Earn'), ('spend', 'Spend'), ('bonus', 'Bonus'), ('refund', 'Refund'), ('admin_adjustment', 'Admin adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', help_text='e.g. a GameSession or Hint-request public_id.', max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.creditaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='gamificatio_account_259702_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('account', 'reference'), name='unique_credit_reference_per_account')],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='gamification.badge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.studentprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'badge'), name='unique_badge_per_student')],
            },
        ),
        migrations.CreateModel(
            name='XPTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('game', 'Game'), ('quiz', 'Quiz'), ('daily_challenge', 'Daily challenge'), ('milestone', 'Milestone'), ('admin_adjustment', 'Admin adjustment')], max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='gamification.xpaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'created_at'], name='gamificatio_account_edfac9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('account', 'reference'), name='unique_xp_reference_per_account')],
            },
        ),
    ]
