# Generated by Django 6.1 on 2026-09-13 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0002_alter_topic_options'),
        ('games', '0004_remove_game_games_game_topic_i_3eb68c_idx_and_more'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('coin_reward', models.PositiveIntegerField(default=25)),
                ('active_date', models.DateField(db_index=True)),
                ('is_published', models.BooleanField(default=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='games.game')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='assessments.quiz')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_challenges', to='curriculum.topic')),
            ],
            options={
                'ordering': ['-active_date'],
            },
        ),
    ]
